from flet import colors

# main colors
CUSTOM_PRIMARY_COLOR = "#DDBB30"
CUSTOM_BGCOLOR = colors.WHITE
CUSTOM_TEXT_COLOR = colors.BLACK

# headers colors
CUSTOM_TEXT_HEADER_COLOR = "#DDBB30"

# BORDER COLOR
CUSTOM_BORDER_COLOR = colors.GREY_100

# SIDE BAR COLORS
CUSTOM_SIDEBAR_COLOR = "#F5F5F5"
CUSTOM_SIDEBAR_ICON_COLOR = "868E96"
CUSTOM_SIDEBAR_TEXT_COLOR = "868E96"

# DAHSBOARD COLORS
CUSTOM_DASHBOARD_COLOR = "#F5F5F5"
CUSTOM_DASHBOARD_BG_COLOR = "#FAFDFB"
